export const tables = {
  ibkr: {
    transactions: [
      ["id", "VARCHAR PRIMARY KEY"],
      ["conid", "INT"],
      ["cur", "CHAR(3) NOT NULL"],
      ["date", "DATETIME NOT NULL"],
      ["fxRate", "DECIMAL(38,5) NOT NULL"],
      ["pr", "DECIMAL(38,2)"],
      ["qty", "SMALLINT"],
      ["acctid", "VARCHAR NOT NULL"],
      ["amt", "DECIMAL(38,5) NOT NULL"],
      ["type", "VARCHAR NOT NULL"],
      ["desc", "VARCHAR NOT NULL"],
    ],
  },
  all: {
    accounts: [
      ["a_id", "VARCHAR PRIMARY KEY"],
      ["a_id_original", "VARCHAR NOT NULL"],
      ["broker", "CHAR(4) NOT NULL"],
      ["alias", "VARCHAR NOT NULL"],
      ["currency", "CHAR(3) NOT NULL"],
    ],
    positions: [
      ["p_id", "VARCHAR PRIMARY KEY"],
      ["con_id", "VARCHAR NOT NULL"],
      ["broker", "CHAR(4) NOT NULL"],
      ["a_id", "VARCHAR NOT NULL"],
      ["description", "VARCHAR NOT NULL"],
      ["ticker", "VARCHAR NOT NULL"],
      ["currency", "CHAR(3) NOT NULL"],
      ["exchange", "VARCHAR NOT NULL"],
      ["position", "SMALLINT"],
      ["fx_market", "DECIMAL(38,8) NOT NULL"],
      ["fx_buy", "DECIMAL(38,8) NOT NULL"],
      ["date", "INT NOT NULL"],
      ["price_market", "DECIMAL(38,8) NOT NULL"],
      ["price_buy", "DECIMAL(38,8) NOT NULL"],
    ],
  },
} as const;
